### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [apb165/prj-rev-bwfs-dasmoto#3]
(Simplify) Alternatively, you can specify shared properties for multiple elements by including all the selectors separated by commas:

```css
h1, h2, p {
  font-family: Helvetica;
}
```

https://github.com/apb165/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/index.css#L1-L17
